services:
  survivor-back:
    build:
      context: .
      dockerfile: "./back/Dockerfile"
    ports:
      - "3000:3000"
  survivor-front:
    build:
      context: .
      dockerfile: "./front/Dockerfile"
    ports:
      - "5000:5000"